# Site settings
title: Vivek Pimprikar 
email: pimprikar.vivek555@gmail.com
description: This is my blog
  Jekyll Theme Demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pimprikarvivek.github.io" # the base hostname & protocol for your site
github_username: pimprikarvivek

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
